### ISSUE TITLE
Wooden Mechanical Parts have no texture

### ISSUE THREAD

**Issue by Amperthorpe** [Terasology/JoshariasSurvival#11]
http://i.imgur.com/0jHTQbE.png

No module changed from defaults.

**Comment by Josharias** [comment]
Thank you for the report.  I have this fixed somewhere, I will make sure it gets in the next release.

**Comment by Josharias** [comment]
Fixed in https://github.com/Terasology/IRLCorp/commit/7cf2817077a30210e4b4ae0c34c97e22d4a446b2.  This also has made it to the recent omega release.
