### ISSUE TITLE
Double `e` click needed sometimes to open a workstation

### ISSUE THREAD

**Issue by Cervator** [Terasology/JoshariasSurvival#15]
If I place the initial work station I sometimes need to `e` click it twice before it'll open. Seems to be in part from having opened the regular inventory first, as if something in it isn't letting go of something.

Found a similar situation with the bookcase in Books recently, where there was some broken fragment in a prefab somewhere. Maybe some part of the inventory is loose?

If I `i` click a bunch I see the "Assemble" button show up briefly, then it disappears (as there isn't anything ready to assemble yet). Unsure if related but wanted to also mention that :-)

**Comment by portokaliu** [comment]
This might actually be related to the fact that the last interaction entity is still considered being interacted with until a 2nd time `e` is pressed. As such, first e on the item activates it, 2nd e anywhere closes it (even though you might've closed the menu before then). I'll look into it later on

**Comment by Cervator** [comment]
Do you think that's specific to the interaction screen setup then, which is in engine, not here? I noticed you still need two times `e` to open stuff after the hotfix PR to engine - despite I guess the first attempt having a valid entity now.

**Comment by portokaliu** [comment]
Yes, I believe we need some work on leaving the "interaction" with said block. I'm not sure at the moment, but I suspect that the first time on a server when you try to access a block it should work on the first `e` click. Afterwards only after a second `e` click

**Comment by Cervator** [comment]
Something is coming back to me - when you close an assembly table with `ESC` you have to use double `e` to get back. When you close an open assembly table by `e` clicking again the *next* try indeed only takes one `e` click. We've had issues with `ESC` closing differing from other stuff in the past.

While technically the first time I try to open an assembly table it takes two `e` clicks at that point I will have already used `ESC` to close the inventory that I had to use to craft the assembly table in the first place, as it doesn't want to close with `i` - instead that `i` seems like it is trying to re-open the inventory (briefly you can see the "Assemble" button until it disappears as there's no valid recipe loaded.

**Comment by portokaliu** [comment]
The inventory itself is also used as an interaction target, so that's most likely the reason for that. We need to cover any aspect of an inventory closing, not just the opening one. That should fix about every problem :D

**Comment by Cervator** [comment]
Closing as fixed by https://github.com/MovingBlocks/Terasology/pull/2703 :-)
