### ISSUE TITLE
Overlapping notification pop-ups between InGameHelp and eventualskills

### ISSUE THREAD

**Issue by Josharias** [Terasology/JoshariasSurvival#16]
When the in game help and eventual skills are shown,  I want them not to overlap so that they can be seen.

Could use either:
1. A module setting/configuration mechanism provided already by the engine to add some coordinates for each popup.
2. Overriding the .ui file in this gameplay module and giving them a compatible layout.

**Comment by skaldarnar** [comment]
This is solved by using the https://github.com/Terasology/Notifications module now.
