### ISSUE TITLE
Ore chunk duplication glitch and general chunk bugginess

### ISSUE THREAD

**Issue by dkambersky** [Terasology/JoshariasSurvival#20]
Stumbled upon two things today - worth noting, those are both client-side, and other players don't see it / it doesn't persist through relogs.

- When two types of chunks are combined in the inventory, the items get effectively duplicated, with . 
--  Example: try placing a stack of '3x Copper Chunks' on '1x Coal Chunks'. You now have '3x Copper Chunks' and '4x Coal Chunks'

- Then there is a harder to reproduce issue with combining chunks, possibly unsifted with sifted, which turns the stack client-side into a '?'.  Relogging fixes the issue.

**Comment by skaldarnar** [comment]
Closing as likely outdated.
