### ISSUE TITLE
Update to `SimpleFarming` 2.0

### ISSUE THREAD

**Issue by aaron-harris** [Terasology/JoshariasSurvival#22]
The Joshaberry bushes haven't been updated to incorporate @jellysnake's recent changes to `SimpleFarming`.  I just looked them over, and most of the changes look pretty straightforward, with a couple of exceptions.  Some thoughts:

* Getting world-generated bushes to spawn in a harvestable state looks tricky.

* The image used for the Joshaberry seed no longer exists.  Since the other bits re-use the blueberry assets, it probably makes sense to get rid of the seed and have the berries be directly plantable, as with the SimpleFarming blueberry bush.  In trying this out, though, I kept accidentally eating berries I was intending to plant.

* Alternatively, maybe the bushes themselves should be deleted and replaced with the `SimpleFarming` blueberry bush.  We could use deltas to increase the growth times (since the `SimpleFarming` bushes grow super-quickly for easy testing).  We'd still need to solve the problem with world-generated bushes, though.

**Comment by Cervator** [comment]
So noticing this now has #21 making a little more sense to me - if indeed you _merge_ the seed and berry items then behavior gets weird. Right click seed -> plant seed, but right click berry -> eat berry

That gets a little tricky. Again reminds me of the quirks with drinking, which also is a thing in JS. Right click with a cup of water -> drink - unless you happen to be pointing at a block in which case it attempts to _water_ the block (like filling a tank)

At any point where holding an item can result in multiple different actions we need better clarity. One past idea has been adding a radial menu for non-default options. So with the hypothetical berry item that has been merged with the seed functionality you might get:

* Left click = break target block as always (or attack a creature, etc) - held item may modify damage but not change the action
* `e` click = activate target block as always (which in this case again doesn't get modified by holding a berry/seed - unless perhaps you're `e` clicking another bush which could add to the stack associated with the held berry)
* Right click = default item action, in the case of the berry probably eating it (likely trying to eat something would be higher priority than planting something)
* *Hold down* right mouse button = engage radial menu showing all possible actions associated with the held item. Options include eat (default), plant, maybe smush the berries into a paste (could reveal the actual seeds or result in your hand turning blue). 

Exact radial options available would depend on player state - where you are, what are you pointing at, maybe even what have you learned (skill system). Actions outside current context could still be present in a radial menu but be grayed out (such as "plant berry" when you are pointing at the sky). The default action chosen with a simple click could also take context into approach, so right click berry when looking at sky -> eat berry; right click berry when looking at grass block -> plant berry as seed. For anybody disliking radial menus or having challenges working one making the default context sensitive might help speed things along / improve UX.

How does that sound?

As far as the fate of the Joshaberry itself goes they used to be straight up blueberries, and the rename was just to resolve the name conflict vs the blueberry in SimpleFarming. So if that system is more ready to take over now we could just delete the Joshaberry and rely on SimpleFarming placing its plants into the world normally :-)

**Comment by aaron-harris** [comment]
I like the radial menu idea quite a bit, especially since it allows for open-ended extension pretty easily.

I'm not sure how I feel about the default action being eating, or rather that it is that easy to eat things by mistake.  Maybe that's just too much familiarity with Minecraft, where you have to hold down the right mouse button to eat, and you get feedback that that's what's happening.

My own personal preference, which I do not expect to be universal, would be:

* Left click: Break target block.
* `e` key: Activate target block.
* Right click: Plant berry, if possible.
* Hold right click: Eat berry.
* Hold middle click: Open radial menu.

In order to support that setup, I would allow each item to specify both a primary action and a secondary action, and then create actions/commands/things-bindable-to-keys for:

* Break target block (my left click, your left click)
* Activate target block (my `e`, your `e`)
* Primary function (my right click)
* Secondary function (my hold right click)
* Context-sensitive/DWIM function (try primary, then secondary) (your right click)
* Radial menu (my hold middle click, your hold right click)

If we allow all of those to be bound freely (and let hold right click be bound independently of ordinary right click), then we can support both configurations, and others.

**Comment by Cervator** [comment]
So I ended up bumping the dependency on SimpleFarming to v2 just so you could actually have the dependencies resolve and launch JS. I did a minimal fix just to rebase the Joshaberry on the new "generic" bush - but it doesn't actually work from world gen yet. It just doesn't crash.

When the new system is fully ready we can probably deprecate or move the Joshaberry and not keep any fruit stuff in this module itself. Pinging @jellysnake for awareness :-)

**Comment by syntaxi** [comment]
So SimpleFarming doesn't gave world gen (or even content any more)
CommonEdibleFlora is the one with the world gen plugin, so that should probably be enabled.

**Comment by skaldarnar** [comment]
Technically this module is using SimpleFarming v2.+ by now. There are berry and fruit bushes spawning in the world which can be harvested, and newly planted bushes will grow over time.

I'm closing this issue as "complete", and we can create more concrete tasks on how advance farming in JS in the future.
