### ISSUE TITLE
Items: Unable to fill wooden cup or wooden bucket with liquid

### ISSUE THREAD

**Issue by SlintVox** [Terasology/JoshariasSurvival#27]
When the user attempts to fill a bucket or cup, they are unable to fill it with water or lava.

**Repro steps:**
1. Go into world with JoshariasSurvival mod active.
2. Press `f1` to open command prompt.
3. Get wooden cup using `give WoodenCup`.
4. Get wooden bucket using `give WoodenBucket`.
5. Find body of water/lava.
**Another option:**
     1. Use `give Core:Water` or `give Core:Lava`  in command prompt
     2. Dig a few holes and put in water/lava block(s) in the dug up hole.
6.  Equip cup/bucket and right click (Test both)
**Expected:** Cup/bucket should be filled with liquid that was right clicked on.
**Actual:** Cup/bucket does not fill with selected liquid.

**Comment by jdrueckert** [comment]
Fixed by  Terasology/Fluid#15 and Terasology/ManualLabor#27
