### ISSUE TITLE
Lava block is not placing

### ISSUE THREAD

**Issue by nailorcngci** [Terasology/JoshariasSurvival#30]
### Info
When player tries to place lava block; light is placing, lava blocks in inventory are reducing but lava block is not placing.

### How to Reproduce
 
1. Go into `Josharias Survival` through `New Game`
2. Press `f1` to open command prompt
3. Get lava block using `give CoreBlocks:Lava`
4. Place lava block somewhere

**Expected**
Lava block must be placed when player right clicks.
**Actual**
Lava block is not placing.

### Screenies
_Before placing_
![1](https://user-images.githubusercontent.com/44372113/70562885-50a51400-1b9e-11ea-98da-4c63d61d06bc.png)
_Placing_
![2](https://user-images.githubusercontent.com/44372113/70562887-50a51400-1b9e-11ea-8387-50655afc2026.png)
_After placing_
![3](https://user-images.githubusercontent.com/44372113/70562888-50a51400-1b9e-11ea-8591-9e178a02a2dd.png)

**Comment by nailorcngci** [comment]
and a screenshot from Core(works totally normal)
![4](https://user-images.githubusercontent.com/44372113/70564358-1721d800-1ba1-11ea-9e12-c93f010218cc.png)

**Comment by Cervator** [comment]
Well illustrated, thanks for the report 👍 

Going to add this to the triage board for the engine just for added visibility

**Comment by skaldarnar** [comment]
I'm curious whether this is a "rendering" issue. We've noticed something similar about the berry bushes when testing in multiplayer some time ago, where blocks were disappearing for me, but were still visible for @jdrueckert.

Sometimes re-connecting fixed it, or at least another client was able to see (and interact with) the block just fine.

**Comment by Cervator** [comment]
There's a new release candidate out after _a lot_ of rebuilding and updates and I can no longer replicate this. Going to close with the expectation that we either dislodged the issue via rebuilds or fixed it coincidentally :-)
