### ISSUE TITLE
Character Screen and Journal don't show

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/JoshariasSurvival#42]
The UI screens for character (`C`) and journal (`J`) don't show on pressing the respective hotkeys.
Reported on Discord by user "rodario".
Reproduced by @skaldarnar in Terasology Nightly 1103.

The root cause seems to be that the following modules are not activated by default in JS:
* `Anatomy`
* `BasicCrafting`
* `Equipment`
* `Journal`
* `WorkstationCrafting`

**Comment by DarkWeird** [comment]
Probably dependency modules for JS not activates.
Ui screens begans works after force modules activation

**Comment by jdrueckert** [comment]
The modules listed above are no dependencies of JS. We need to check which should be. In general the keybinding settings menu currently shows bindings associated with not activated modules as well, which needs to be changed.

**Comment by skaldarnar** [comment]
I think this is rather an issue about which settings we show, e.g., key bindings for modules that are not active but available.

Related to https://github.com/MovingBlocks/Terasology/issues/2588 and https://github.com/MovingBlocks/Terasology/issues/2384,
